"use client";

import { useState } from "react";
import {
  Download,
  ExternalLink,
  CheckCircle2,
  Calendar,
} from "lucide-react";
import usePotentialTransaction from "../../hooks/recommendation-centre/use-potential-transaction";
import { exportToCSV } from "@/utils/csv-export";
import Link from "next/link";
import { usePostTask } from "@/hooks/recommendation-centre/use-task-manager";
import { useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { useToast } from "@/hooks/use-toast";
import { usePagePermissions } from "@/hooks/permissions/use-page-permissions";

export default function OwnedProductTable() {
  const [profitTaken, setProfitTaken] = useState<Set<string>>(new Set());
  const [appointmentCreated, setAppointmentCreated] = useState<Set<string>>(
    new Set()
  );

  // Hooks
  const { data, isLoading, error } = usePotentialTransaction();
  const potentialTransactions = data?.potential_transaction || [];
  const { mutateAsync: createTask } = usePostTask();
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const { canView } = usePagePermissions();

  const handleExport = () => {
    const exportData = potentialTransactions.map((t) => ({
      "Customer ID": t.id_nasabah,
      "Product Name": t.nama_produk,
      "Profit/Loss (%)": t.profit,
      Status: t.profit > 0 ? "Ambil Profit" : "Janji Temu",
    }));
    exportToCSV(exportData, "potential_transactions");
  };

  // Handle "Ambil Profit" click
  const handleAmbilProfit = (customerId: string, productName: string) => {
    setProfitTaken((prev) => new Set(prev).add(`${customerId}-${productName}`));
    toast({
      title: "Profit Diambil",
      description: `Profit untuk ${productName} telah ditandai sebagai diambil`,
      variant: "default",
    });
  };

  // Handle "Janji Temu" click - Create task
  const handleJanjiTemu = async (customerId: string, productName: string) => {
    try {
      const today = format(new Date(), "yyyy-MM-dd");
      const taskDescription = `Janji Temu - ${productName}`;

      // Create task with customer ID as invitee
      await createTask({
        id: "", // Will be generated by backend
        description: taskDescription,
        invitee: customerId,
        due_date: today,
      });

      // Mark as created
      setAppointmentCreated((prev) =>
        new Set(prev).add(`${customerId}-${productName}`)
      );

      // Invalidate task query to refresh task manager
      queryClient.invalidateQueries({ queryKey: ["task"] });

      toast({
        title: "Task Berhasil Dibuat",
        description: `Janji temu untuk ${customerId} telah ditambahkan ke Task Manager`,
        variant: "default",
      });
    } catch (error: any) {
      // Check if it's a permission error - if so, the interceptor already showed the error
      const errorMessage = error?.response?.data?.error || error?.message || "";
      const isPermissionError =
        errorMessage.includes("403") ||
        errorMessage.toLowerCase().includes("permission") ||
        errorMessage.toLowerCase().includes("access denied");

      if (!isPermissionError) {
        // Only show custom error if it's not a permission error
        console.error("Failed to create task:", error);
        toast({
          title: "Kesalahan",
          description: errorMessage || "Gagal membuat task. Silakan coba lagi.",
          variant: "destructive",
        });
      }
      // If it's a permission error, the interceptor already showed the error message
    }
  };

  if (isLoading) {
    return (
      <div className="p-4 flex items-center justify-center h-[310px]">
        <div className="animate-pulse text-gray-600 dark:text-gray-300">
          Loading potential transaction data...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 text-red-600 dark:text-red-400">
        Error loading potential transaction data: {error.message}
      </div>
    );
  }

  return (
    <>
      <div className="h-[310px] flex flex-col mb-3">
        <div className="flex justify-between items-center px-4 py-2 border-b border-gray-200 dark:border-gray-700">
          <h2 className="text-lg font-bold text-black dark:text-white">
            Transaksi Potensial
          </h2>
          {potentialTransactions.length > 0 && (
            <button
              onClick={handleExport}
              className="flex items-center gap-2 px-3 py-1.5 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors text-sm"
              title="Export to CSV"
            >
              <Download size={14} />
              <span>Unduh</span>
            </button>
          )}
        </div>
        <div className="flex-1 overflow-auto rounded-2xl">
          <table className="divide-y-2 divide-gray-900 text-sm text-center w-full text-black dark:text-white">
            <thead className="sticky top-0 bg-white dark:bg-[#1D283A] z-10">
              <tr>
                <th className="py-2">ID Nasabah</th>
                <th className="py-2">Nama Produk</th>
                <th className="py-2">Untung/Rugi (%)</th>
                <th className="py-2">Aksi</th>
                <th className="py-2">Info</th>
              </tr>
            </thead>
            <tbody className="divide-y-2 divide-gray-900">
              {potentialTransactions?.map((product, index) => (
                <tr
                  key={index}
                  className="hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                >
                  <td className="py-2">{product.id_nasabah}</td>
                  <td className="py-2">{product.nama_produk}</td>
                  <td className="py-2">
                    <span
                      className={
                        product.profit > 0
                          ? "text-green-500 font-semibold"
                          : "text-red-500 font-semibold"
                      }
                    >
                      {product.profit > 0
                        ? `+${product.profit}%`
                        : `${product.profit}%`}
                    </span>
                  </td>
                  <td className="p-2">
                    <div className="flex justify-center items-center">
                      {product.profit > 0 ? (
                        <button
                          onClick={() =>
                            handleAmbilProfit(
                              product.id_nasabah,
                              product.nama_produk
                            )
                          }
                          disabled={profitTaken.has(
                            `${product.id_nasabah}-${product.nama_produk}`
                          )}
                          className={`px-3 py-1 text-xs font-medium rounded-md transition-all ${
                            profitTaken.has(
                              `${product.id_nasabah}-${product.nama_produk}`
                            )
                              ? "text-white bg-gray-500 cursor-not-allowed flex items-center gap-1"
                              : "text-white bg-green-500 hover:bg-green-600 cursor-pointer"
                          }`}
                          title={
                            profitTaken.has(
                              `${product.id_nasabah}-${product.nama_produk}`
                            )
                              ? "Profit sudah diambil"
                              : "Klik untuk menandai profit diambil"
                          }
                        >
                          {profitTaken.has(
                            `${product.id_nasabah}-${product.nama_produk}`
                          ) ? (
                            <>
                              <CheckCircle2 size={12} />
                              Profit Diambil
                            </>
                          ) : (
                            "Ambil Profit"
                          )}
                        </button>
                      ) : (
                        <button
                          onClick={() =>
                            handleJanjiTemu(
                              product.id_nasabah,
                              product.nama_produk
                            )
                          }
                          disabled={appointmentCreated.has(
                            `${product.id_nasabah}-${product.nama_produk}`
                          )}
                          className={`px-3 py-1 text-xs font-medium rounded-md transition-all flex items-center gap-1 ${
                            appointmentCreated.has(
                              `${product.id_nasabah}-${product.nama_produk}`
                            )
                              ? "text-white bg-gray-500 cursor-not-allowed"
                              : "text-black bg-yellow-500 hover:bg-yellow-600 cursor-pointer"
                          }`}
                          title={
                            appointmentCreated.has(
                              `${product.id_nasabah}-${product.nama_produk}`
                            )
                              ? "Task sudah dibuat"
                              : "Klik untuk membuat task di Task Manager"
                          }
                        >
                          {appointmentCreated.has(
                            `${product.id_nasabah}-${product.nama_produk}`
                          ) ? (
                            <>
                              <CheckCircle2 size={12} />
                              Task Dibuat
                            </>
                          ) : (
                            <>
                              <Calendar size={12} />
                              Janji Temu
                            </>
                          )}
                        </button>
                      )}
                    </div>
                  </td>
                  <td className="py-2">
                    {canView ? (
                      <Link
                        href={`/customer-details?customerID=${product.id_nasabah}`}
                        className="inline-flex items-center gap-1 px-3 py-1.5 bg-[#01ACD2] hover:bg-[#0199b8] text-white rounded-md transition-colors text-xs"
                      >
                        Profil
                        <ExternalLink size={12} />
                      </Link>
                    ) : (
                      <button
                        disabled
                        className="inline-flex items-center gap-1 px-3 py-1.5 bg-gray-400 text-white rounded-md cursor-not-allowed text-xs opacity-50"
                      >
                        Profil
                        <ExternalLink size={12} />
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
