name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy code into Staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.AWS_USER }}/wealth-ai"
          timeout: 5m

      - name: Setup Build Environment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USER }}/wealth-ai
            docker compose pull || exit 1

      - name: Build and Start Docker Containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AWS_USER }}/wealth-ai
            docker compose up -d --build || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    timeout-minutes: 15
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            echo "Deploying to ${{ secrets.AWS_HOST }}..."
            cd /home/${{ secrets.AWS_USER }}/wealth-ai

            # Restart containers
            docker compose restart || exit 1

            # Wait for services to be healthy
            echo "Waiting for services to be healthy..."
            sleep 30

            # Check if services are running
            if ! docker compose ps | grep -q "Up"; then
              echo "Error: Services failed to start properly"
              exit 1
            fi

            echo "Deployment completed on ${{ secrets.AWS_HOST }}"

            # Cleanup unused images and containers (but keep volumes)
            docker system prune -f --filter "until=24h"
